name: Deploy Grafana

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'v1.20.0'

    - name: Set up GKE
      uses: google-github-actions/setup-gcloud@master
      with:
        version: '290.0.1'
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Authenticate to GKE
      run: gcloud container clusters get-credentials my-gke-cluster --zone us-central1-c --project my-gcp-project

    - name: Annotate existing ClusterRole
      run: |
        kubectl annotate clusterrole my-grafana-clusterrole meta.helm.sh/release-name=my-grafana --overwrite
        kubectl annotate clusterrole my-grafana-clusterrole meta.helm.sh/release-namespace=grafana --overwrite

    - name: Add Helm repository
      run: helm repo add grafana https://grafana.github.io/helm-charts

    - name: Update Helm repositories
      run: helm repo update

    - name: Install Grafana
      run: helm install my-grafana grafana/grafana --namespace grafana --create-namespace
